baseURL: https://www.jexetic.com
languageCode: en-us
title: Jexetic's Blog
theme: "PaperMod"
params:
    homeInfoParams:
        Title: Hi, I'm Jexetic ğŸ‘‹ğŸ»
        Content: Thanks for visiting my blog, a place for my to post all my random thoughts.